config/routes.rb
Homework::Application.routes.draw do
  root 'main#root'
  get '/lessons/:month_day'    => 'main#single_lesson'
  get '/exercises/:month_day/:order_in_lesson' => 'main#single_exercise'

  get  '/login'                => 'main#login'
  get  '/auth/github/callback' => 'main#login_from_github'
  post '/logout'               => 'main#logout'

  # use scope instead of namespace so I don't have to rewrite all
  # the scaffolding path helper calls.
  scope '/admin' do
    resources :users,         controller: 'admin/users'
    resources :repos,         controller: 'admin/repos'
    resources :exercises,     controller: 'admin/exercises'
    resources :refreshes,     controller: 'admin/refreshes'
    resources :lesson_plans,  controller: 'admin/lesson_plans'
    resources :commits,       controller: 'admin/commits'
    resources :sidebar_links, controller: 'admin/sidebar_links'
  end

  post '/github_webhook' => 'main#github_webhook'
end

app/models/lesson_plan.rb
class LessonPlan < ActiveRecord::Base
  has_many :exercises, order: :order_in_lesson

  validates :date,    presence: true
  validates :content, presence: true
  validates :topic,   presence: true
  validates :date,    uniqueness: true

  before_validation :parse_content_for_handout_and_topic
  validate :exercises_can_be_created

  def parse_content_for_handout_and_topic
    self.content.split(/\r?\n/).each_with_index do |line, line_num0|
      # For example, if content has "* 10-07: HTML", set topic to "HTML"
      if match = line.match(/^\* (.*)$/)
        topic = match[1]
        topic = topic[(topic.index(':') + 2)..-1] if topic.include?(':')
        self.topic = topic
      end

      if match = line.match(/^HANDOUT (https?:.*)$/)
        self.handout_url = match[1]
      end
    end
  end

  def exercises_can_be_created
    self.create_exercises
  end

  def create_exercises!
    Exercise.transaction do
      self.exercises.each { |exercise| exercise.destroy }
      exercises = self.create_exercises
      exercises.each { |exercise| exercise.save! }
    end
  end

  def create_exercises
      in_exercise = false
      exercises = []
      exercise_num_indents = 0
      self.content.split(/\r?\n/).each_with_index do |line, line_num0|
        match = line.match(/^( *)([-+] )?(X([0-9]*) ?)?(.*)$/)

        num_indents = match[1].size
        if num_indents % 2 == 1
          errors.add :base, "Odd number of indents at line #{line_num0 + 1}"
        end

        if match[3]
          in_exercise = true
          exercise_num_indents = num_indents
          exercise = Exercise.new({
            lesson_plan_id: self.id,
            exercise_dir: (match[4] == '') ? nil : match[4],
            first_line: match[5],
            content: match[5],
            order_in_lesson: exercises.size + 1,
          })
          if exercise.first_line == nil || exercise.first_line.strip == ''
            errors.add :base,
              "Exercise is missing description at line #{line_num0 + 1}"
          end
          exercises.push exercise
        elsif num_indents <= exercise_num_indents
          in_exercise = false
        elsif in_exercise
          line = ' ' * (num_indents - exercise_num_indents)
          line += match[2] if match[2] && num_indents > exercise_num_indents
          line += match[5]
          exercises.last.content += "\n" + line
        end
      end
      exercises
  end

  def topic_as_html
    self.topic.gsub(/`(.*?)`/, '<code>\\1</code>').html_safe
  end

  def content_as_html
    last_num_indents = 0
    exercise_num = 0

    lines = self.content.split(/\r?\n/).map do |line|

      line.gsub! /</, '&lt;'
      line.gsub! />/, '&gt;'
      line.gsub! /`(.*?)`/, '<code>\\1</code>'
      if line.include?('HANDOUT')
        line.gsub! /HANDOUT (https?:.*)$/,
          "<a target='_blank' href='\\1'>Handout</a>"
      else
        line.gsub! /(https?:\/\/[^\n ,]+)/,
          "<code><a target='_blank' href='\\1'>\\1</a></code>"
      end

      if match = line.match(/^\* (.*)$/)
        num_indents = 0
        line = '' # remove h1
      elsif match = line.match(/^\*\* (.*)$/)
        num_indents = 0
        line = "<h2>#{match[1]}</h2>" # convert ** to h2
      else
        match = line.match(/^( *)([-+] )?(X([0-9]*) ?)?(.*)$/)
        num_indents = match[1].size + (match[2] || '').size

        line = match[5]

        possible_class = ''
        possible_intro = ''
        if match[3]
          exercise_num += 1
          possible_class = "exercise"
          if match[4] != ''
            possible_intro = "<b><a href='/exercises/#{self.date.strftime('%m-%d')}/#{exercise_num}'>Exercise #{exercise_num} in #{match[4]}</a></b> "
          else
            possible_intro = "<b><a href='/exercises/#{self.date.strftime('%m-%d')}/#{exercise_num}'>Exercise #{exercise_num}</a></b> "
          end
        end

        if match[2] == '- '
          line = "<li class='#{possible_class}'>#{possible_intro}" + line
        elsif match[2] == '+ '
          line = "<li class='expandable #{possible_class}'>#{possible_intro}" +
            line
        elsif match[5] != '' # if not blank line
          line = '<br>' + line
        end
      end

      while num_indents > last_num_indents
        line = '<ul>' + line
        last_num_indents += 2
      end

      while num_indents < last_num_indents
        line = '</ul>' + line
        last_num_indents -= 2
      end

      last_num_indents = num_indents

      line
    end

    while last_num_indents > 0
      last_num_indents -= 2
      lines += ['</ul>']
    end

    lines.join("\n").html_safe
  end
end

app/controllers/admin/lesson_plans_controller.rb
class Admin::LessonPlansController < ApplicationController
  before_action :user_must_be_admin
  before_action :set_lesson_plan, only: [:show, :edit, :update, :destroy]

  # GET /lesson_plans
  # GET /lesson_plans.json
  def index
    @lesson_plans = LessonPlan.all
  end

  # GET /lesson_plans/1
  # GET /lesson_plans/1.json
  def show
  end

  # GET /lesson_plans/new
  def new
    @lesson_plan = LessonPlan.new
  end

  # GET /lesson_plans/1/edit
  def edit
  end

  # POST /lesson_plans
  # POST /lesson_plans.json
  def create
    @lesson_plan = LessonPlan.new(lesson_plan_params)

    respond_to do |format|
      if @lesson_plan.save
        format.html { redirect_to @lesson_plan, notice: 'Lesson plan was successfully created.' }
        format.json { render action: 'show', status: :created, location: @lesson_plan }
      else
        format.html { render action: 'new' }
        format.json { render json: @lesson_plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lesson_plans/1
  # PATCH/PUT /lesson_plans/1.json
  def update
    respond_to do |format|
      if @lesson_plan.update(lesson_plan_params)
        @lesson_plan.create_exercises!

        format.html { redirect_to @lesson_plan, notice: 'Lesson plan was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @lesson_plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lesson_plans/1
  # DELETE /lesson_plans/1.json
  def destroy
    @lesson_plan.destroy
    respond_to do |format|
      format.html { redirect_to lesson_plans_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lesson_plan
      @lesson_plan = LessonPlan.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lesson_plan_params
      params.require(:lesson_plan).permit(:date, :content, :topic, :handout_url)
    end
end

app/controllers/lesson_plans_controller.rb
class LessonPlansController < ApplicationController
  before_action :set_lesson_plan, only: [:show, :edit, :update, :destroy]

  # GET /lesson_plans
  # GET /lesson_plans.json
  def index
    @lesson_plans = LessonPlan.all
  end

  # GET /lesson_plans/1
  # GET /lesson_plans/1.json
  def show
  end

  # GET /lesson_plans/new
  def new
    @lesson_plan = LessonPlan.new
  end

  # GET /lesson_plans/1/edit
  def edit
  end

  # POST /lesson_plans
  # POST /lesson_plans.json
  def create
    @lesson_plan = LessonPlan.new(lesson_plan_params)

    respond_to do |format|
      if @lesson_plan.save
        format.html { redirect_to @lesson_plan, notice: 'Lesson plan was successfully created.' }
        format.json { render action: 'show', status: :created, location: @lesson_plan }
      else
        format.html { render action: 'new' }
        format.json { render json: @lesson_plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lesson_plans/1
  # PATCH/PUT /lesson_plans/1.json
  def update
    respond_to do |format|
      if @lesson_plan.update(lesson_plan_params)
        format.html { redirect_to @lesson_plan, notice: 'Lesson plan was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @lesson_plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lesson_plans/1
  # DELETE /lesson_plans/1.json
  def destroy
    @lesson_plan.destroy
    respond_to do |format|
      format.html { redirect_to lesson_plans_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lesson_plan
      @lesson_plan = LessonPlan.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lesson_plan_params
      params.require(:lesson_plan).permit(:date, :content, :topic, :handout_url)
    end
end

app/helpers/lesson_plans_helper.rb
module LessonPlansHelper
end

app/views/admin/lesson_plans/_form.html.erb
<%= form_for(@lesson_plan) do |f| %>
  <% if @lesson_plan.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@lesson_plan.errors.count, "error") %> prohibited this lesson_plan from being saved:</h2>

      <ul>
      <% @lesson_plan.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content, rows: 10, cols: 100 %>
  </div>
  <% if @lesson_plan.id %>
    <div class="field">
      <%= f.label :topic %><br>
      <%= f.text_field :topic, size: 100 %>
    </div>
    <div class="field">
      <%= f.label :handout_url %><br>
      <%= f.text_field :handout_url, size: 100 %>
    </div>
  <% end %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/lesson_plans/edit.html.erb
<h1>Editing lesson_plan</h1>

<%= render 'form' %>

<%= link_to 'Show', @lesson_plan %> |
<%= link_to 'Back', lesson_plans_path %>

app/views/admin/lesson_plans/index.html.erb
<h1>Listing lesson_plans</h1>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Content</th>
      <th>Topic</th>
      <th>Handout url</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @lesson_plans.each do |lesson_plan| %>
      <tr>
        <td><%= lesson_plan.date %></td>
        <td><pre><%= lesson_plan.content %></pre></td>
        <td><%= lesson_plan.topic %></td>
        <td><%= lesson_plan.handout_url %></td>
        <td><%= link_to 'Show', lesson_plan %></td>
        <td><%= link_to 'Edit', edit_lesson_plan_path(lesson_plan) %></td>
        <td><%= link_to 'Destroy', lesson_plan, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Lesson plan', new_lesson_plan_path %>

app/views/admin/lesson_plans/new.html.erb
<h1>New lesson_plan</h1>

<%= render 'form' %>

<%= link_to 'Back', lesson_plans_path %>

app/views/admin/lesson_plans/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @lesson_plan.date %>
</p>

<p>
  <strong>Content:</strong>
  <pre><%= @lesson_plan.content %></pre>
</p>

<p>
  <strong>Topic:</strong>
  <%= @lesson_plan.topic %>
</p>

<p>
  <strong>Handout url:</strong>
  <%= @lesson_plan.handout_url %>
</p>

<%= link_to 'Edit', edit_lesson_plan_path(@lesson_plan) %> |
<%= link_to 'Back', lesson_plans_path %>