config/routes.rb
Homework::Application.routes.draw do
  root 'main#root'
  get '/lessons/:month_day'    => 'main#single_lesson'
  get '/exercises/:month_day/:order_in_lesson' => 'main#single_exercise'

  get  '/login'                => 'main#login'
  get  '/auth/github/callback' => 'main#login_from_github'
  post '/logout'               => 'main#logout'

  # use scope instead of namespace so I don't have to rewrite all
  # the scaffolding path helper calls.
  scope '/admin' do
    resources :users,         controller: 'admin/users'
    resources :repos,         controller: 'admin/repos'
    resources :exercises,     controller: 'admin/exercises'
    resources :refreshes,     controller: 'admin/refreshes'
    resources :lesson_plans,  controller: 'admin/lesson_plans'
    resources :commits,       controller: 'admin/commits'
    resources :sidebar_links, controller: 'admin/sidebar_links'
  end

  post '/github_webhook' => 'main#github_webhook'
end

app/models/repo.rb
class Repo < ActiveRecord::Base
  belongs_to :user
  has_many   :repos
  has_many   :refreshes
  has_many   :commits

  validates :user_id,   presence: true
  validates :name,      presence: true
  validates :https_url, presence: true
end

app/controllers/admin/repos_controller.rb
class Admin::ReposController < ApplicationController
  before_action :user_must_be_admin
  before_action :set_repo, only: [:show, :edit, :update, :destroy]

  # GET /repos
  # GET /repos.json
  def index
    @repos = Repo.all
  end

  # GET /repos/1
  # GET /repos/1.json
  def show
  end

  # GET /repos/new
  def new
    @repo = Repo.new
  end

  # GET /repos/1/edit
  def edit
  end

  # POST /repos
  # POST /repos.json
  def create
    @repo = Repo.new(repo_params)

    respond_to do |format|
      if @repo.save
        format.html { redirect_to @repo, notice: 'Repo was successfully created.' }
        format.json { render action: 'show', status: :created, location: @repo }
      else
        format.html { render action: 'new' }
        format.json { render json: @repo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /repos/1
  # PATCH/PUT /repos/1.json
  def update
    respond_to do |format|
      if @repo.update(repo_params)
        format.html { redirect_to @repo, notice: 'Repo was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @repo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /repos/1
  # DELETE /repos/1.json
  def destroy
    @repo.destroy
    respond_to do |format|
      format.html { redirect_to repos_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_repo
      @repo = Repo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def repo_params
      params.require(:repo).permit(:user_id, :name, :https_url, :has_exercise_dirs, :is_not_found)
    end
end

app/controllers/repos_controller.rb
class ReposController < ApplicationController
  before_action :set_repo, only: [:show, :edit, :update, :destroy]

  # GET /repos
  # GET /repos.json
  def index
    @repos = Repo.all
  end

  # GET /repos/1
  # GET /repos/1.json
  def show
  end

  # GET /repos/new
  def new
    @repo = Repo.new
  end

  # GET /repos/1/edit
  def edit
  end

  # POST /repos
  # POST /repos.json
  def create
    @repo = Repo.new(repo_params)

    respond_to do |format|
      if @repo.save
        format.html { redirect_to @repo, notice: 'Repo was successfully created.' }
        format.json { render action: 'show', status: :created, location: @repo }
      else
        format.html { render action: 'new' }
        format.json { render json: @repo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /repos/1
  # PATCH/PUT /repos/1.json
  def update
    respond_to do |format|
      if @repo.update(repo_params)
        format.html { redirect_to @repo, notice: 'Repo was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @repo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /repos/1
  # DELETE /repos/1.json
  def destroy
    @repo.destroy
    respond_to do |format|
      format.html { redirect_to repos_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_repo
      @repo = Repo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def repo_params
      params.require(:repo).permit(:user_id, :url)
    end
end

app/helpers/repos_helper.rb
module ReposHelper
end

app/views/admin/repos/_form.html.erb
<%= form_for(@repo) do |f| %>
  <% if @repo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@repo.errors.count, "error") %> prohibited this repo from being saved:</h2>

      <ul>
      <% @repo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id, 'User ID' %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :https_url %><br>
    <%= f.text_field :https_url %>
  </div>
  <div class="field">
    <%= f.label :hook_id %><br>
    <%= f.number_field :hook_id %>
  </div>
  <div class="field">
    <%= f.label :has_exercise_dirs %><br>
    <%= f.check_box :has_exercise_dirs %>
  </div>
  <div class="field">
    <%= f.label :is_not_found %><br>
    <%= f.check_box :is_not_found %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/repos/edit.html.erb
<h1>Editing repo</h1>

<%= render 'form' %>

<%= link_to 'Show', @repo %> |
<%= link_to 'Back', repos_path %>

app/views/admin/repos/index.html.erb
<h1>Listing repos</h1>

<table border="1">
  <thead>
    <tr>
      <th>User</th>
      <th>Name</th>
      <th>HTTPS URL</th>
      <th>Hook ID</th>
      <th>Has exercise dirs?</th>
      <th>Is not found?</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @repos.each do |repo| %>
      <tr>
        <td><%= repo.user_id %></td>
        <td><%= repo.name %></td>
        <td><%= repo.https_url %></td>
        <td><%= repo.hook_id %></td>
        <td><%= repo.has_exercise_dirs %></td>
        <td><%= repo.is_not_found %></td>
        <td><%= link_to 'Show', repo %></td>
        <td><%= link_to 'Edit', edit_repo_path(repo) %></td>
        <td><%= link_to 'Destroy', repo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Repo', new_repo_path %>

app/views/admin/repos/new.html.erb
<h1>New repo</h1>

<%= render 'form' %>

<%= link_to 'Back', repos_path %>

app/views/admin/repos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @repo.user_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @repo.name %>
</p>

<p>
  <strong>HTTPS URL:</strong>
  <%= @repo.https_url %>
</p>

<p>
  <strong>Hook ID:</strong>
  <%= @repo.hook_id %>
</p>

<p>
  <strong>Has exercise dirs?</strong>
  <%= @repo.has_exercise_dirs %>
</p>

<p>
  <strong>Is not found?</strong>
  <%= @repo.is_not_found %>
</p>

<%= link_to 'Edit', edit_repo_path(@repo) %> |
<%= link_to 'Back', repos_path %>